#!/bin/bash
set -e

CONFIG_FILE=$SNAP_DATA/config.ini

# Create configuration file with default configurations
echo "[watcher]" > $CONFIG_FILE
echo "watch = $SNAP_COMMON/watch" >> $CONFIG_FILE
echo "[organizer]" >> $CONFIG_FILE
echo "library = $SNAP_COMMON/library" >> $CONFIG_FILE

# Create necessary directories
mkdir -p $SNAP_COMMON/watch
mkdir -p $SNAP_COMMON/library
